version: '3.1'

services:

  web:
    image: nginx
    container_name: web
    ports:
     - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web.conf:/etc/nginx/conf.d/web.conf
      - ./www:/www
      - ./logs:/logs
