document.activeElement
document.addEventListener()
document.adoptNode()
document.anchors
document.applets
document.baseURI
document.body
document.close()
document.cookie
document.charset
document.characterSet
document.createAttribute()
document.createComment()
document.createDocumentFragment()
document.createElement()
document.createEvent()
document.createTextNode()
document.defaultView
document.designMode
document.doctype
document.documentElement
document.documentMode
document.documentURI
document.domain
document.domConfig
document.embeds
document.execCommand()
document.forms
document.fullscreenElement
document.fullscreenEnabled()
document.getElementById()
document.getElementsByClassName()
document.getElementsByName()
document.getElementsByTagName()
document.hasFocus()
document.head
document.images
document.implementation
document.importNode()
document.inputEncoding
document.lastModified
document.links
document.normalize()
document.normalizeDocument()
document.open()
document.querySelector()
document.querySelectorAll()
document.readyState
document.referrer
document.removeEventListener()
document.renameNode()
document.scripts
document.strictErrorChecking
document.title
document.URL
document.write()
document.writeln()