var d = new Date();
var d = new Date(milliseconds);
var d = new Date(dateString);
var d = new Date(year, month, day, hours, minutes, seconds, milliseconds);

d.constructor;
d.prototype;

d.getDate();
d.getDay();
d.getFullYear();
d.getHours();
d.getMilliseconds();
d.getMinutes();
d.getMonth();
d.getSeconds();
d.getTime();
d.getTimezoneOffset();
d.getUTCDate();
d.getUTCDay();
d.getUTCFullYear();
d.getUTCHours();
d.getUTCMilliseconds();
d.getUTCMinutes();
d.getUTCMonth();
d.getUTCSeconds();
d.getYear();
d.now();
d.parse();
d.setDate();
d.setFullYear();
d.setHours();
d.setMilliseconds();
d.setMinutes();
d.setMonth();
d.setSeconds();
d.setTime();
d.setUTCDate();
d.setUTCFullYear();
d.setUTCHours();
d.setUTCMilliseconds();
d.setUTCMinutes();
d.setUTCMonth();
d.setUTCSeconds();
d.setYear();
d.toDateString();
d.toGMTString();
d.toISOString();
d.toJSON();
d.toLocaleDateString();
d.toLocaleTimeString();
d.toLocaleString();
d.toString();
d.toTimeString();
d.toUTCString();
d.UTC();
d.valueOf();

