version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./app:/var/www/html
    ports:
      - 9001:80
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - 9002:3306

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - app
