var element  = document.getElementById('el');

element.accessKey
element.addEventListener()
element.appendChild()
element.attributes
element.blur()
element.childElementCount
element.childNodes
element.children
element.classList
element.className
element.click()
element.clientHeight
element.clientLeft
element.clientTop
element.clientWidth
element.cloneNode()
element.compareDocumentPosition()
element.contains()
element.contentEditable
element.dir
element.exitFullscreen()
element.firstChild
element.firstElementChild
element.focus()
element.getAttribute()
element.getAttributeNode()
element.getBoundingClientRect()
element.getElementsByClassName()
element.getElementsByTagName()
element.hasAttribute()
element.hasAttributes()
element.hasChildNodes()
element.id
element.innerHTML = '<span>text</span>';
element.innerText
element.insertAdjacentElement()
element.insertAdjacentHTML()
element.insertAdjacentText()
element.insertBefore()
element.isContentEditable
element.isDefaultNamespace()
element.isEqualNode()
element.isSameNode()
element.isSupported()
element.lang
element.lastChild
element.lastElementChild
element.namespaceURI
element.nextSibling
element.nextElementSibling
element.nodeName
element.nodeType
element.nodeValue
element.normalize()
element.offsetHeight
element.offsetWidth
element.offsetLeft
element.offsetParent
element.offsetTop
element.outerHTML
element.outerText
element.ownerDocument
element.parentNode
element.parentElement
element.previousSibling
element.previousElementSibling
element.querySelector()
element.querySelectorAll()
element.remove()
element.removeAttribute()
element.removeAttributeNode()
element.removeChild()
element.removeEventListener()
element.replaceChild()
element.requestFullscreen()
element.scrollHeight
element.scrollIntoView()
element.scrollLeft
element.scrollTop
element.scrollWidth
element.setAttribute()
element.setAttributeNode()
element.style
element.tabIndex
element.tagName
element.textContent
element.title
element.toString()