version: "3.0"

services:

  salt:
    container_name: salt
    image: saltstack/salt
    ports:
      - 4505:4505
      - 4506:4506
      - 8000:8000
    restart: always
    depends_on:
      - minion
    environment:
      SALT_SHARED_SECRET: mysecretpassword
    volumes:
      - ./srv:/srv
      - ./keys-master:/var/lib/salt/pki
    networks:
      - network1

  minion:
    container_name: minion
    image: minion
    build: .
    restart: "no"
    volumes:
      - ./srv:/srv
      - ./keys-minion:/etc/salt/pki
      - ./minion_id:/etc/salt/minion_id
    networks:
      - network1

networks:
  network1:
    driver: bridge
