version: '3.8'

services:

  pg:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql
    networks:
      - pg
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - pg

  pgadminer:
    container_name: pgadminer
    image: adminer
    restart: always    
    ports:
      - "9999:8080"
    environment:
      ADMINER_DEFAULT_SERVER: pgsql      
    networks:
      - pg

volumes:
  pgdata:

networks:
  pg:
    driver: bridge